ARG DEB_COMPATIBLE_BASE_IMG
FROM ${DEB_COMPATIBLE_BASE_IMG}
RUN apt update
RUN apt-get install -y curl
RUN apt-get install -y binutils gcc dpkg-dev jq lintian pkg-config
RUN cargo install cargo-deb --version 1.38.4
RUN cargo install toml-cli --version 0.2.0